name: ECF

on: push

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore --configuration Release

      - name: Run tests
        run: dotnet test --no-build --configuration Release --collect:"XPlat Code Coverage"

  trivy-scan:
    name: Trivy
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release

      - name: Run Trivy
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: fs
          scan-ref: ./bin/Release
          ignore-unfixed: true
          format: table
          exit-code: 1
          severity: CRITICAL,HIGH,MEDIUM,LOW,UNKNOWN

  # cypress-run:
  #     runs-on: ubuntu-24.04
  #     needs: build
  #     steps:
  #       - name: Checkout
  #         uses: actions/checkout@v4

  #       - name: Setup .NET
  #         uses: actions/setup-dotnet@v4
  #         with:
  #           dotnet-version: '8.0.x'

  #       - name: Restore dependencies
  #         run: dotnet restore

  #       - name: Build
  #         run: dotnet build --configuration Release

  #       - name: Start the application
  #         run: dotnet run
  #         env:
  #           ASPNETCORE_ENVIRONMENT: Development
  #       - name: Cypress run
  #         uses: cypress-io/github-action@v6
  #         with:
  #           start: echo "App already started"
  #           wait-on: http://localhost:7196
  #           wait-on-timeout: 60

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Run tests
        run: dotnet test --no-build --configuration Release --collect:"XPlat Code Coverage"


